# syntax=docker/dockerfile:1.3
# escape=`

FROM debian:latest

LABEL Author="Or Ben Shimon"`
    LABEL Corp="BenShimonTechnologiesLLC"`
    LABEL Project="DomRec"`
    LABEL Version="3"`
    LABEL Minor="Alpha 1.0"
ENV DBCredentials_File = ./DBCredentials.json


CMD []

